[package]
name = "reduce"
edition = "2021"
authors.workspace = true
version.workspace = true
license.workspace = true

[[bin]]
path = "src/reduce.rs"
name = "reduce"

[dependencies]
sha256.workspace = true
